---
title: "Brief Profile"
---

I am Adelusi Bamidele Samuel, an accomplished and dedicated IT professional with a strong background in Computer Science - Software Development, Data Science and Database Administration. Over the years, I have acquired a comprehensive educational foundation and a wealth of practical experience that enables me to contribute significantly to my Professional field. My academic journey began at Yaba College of Technology, Nigeria, where I obtained a degree in Computer Science in 2001, marking the inception of my passion for technology and innovation.

My ongoing pursuit of a Master's degree in Social Data Analytics and Research at the University of Texas at Dallas is an evidence of my determination to stay at the forefront of technological advancements. This program is enhancing my skills in harnessing data to derive insights, enabling me to make informed decisions that bridge the gap between technology and societal needs.

My pursuit of academic excellence led me to acquire a Master's degree in Business Computing (2018) from the University of Ibadan. This program fortified my understanding of the intersection between business operations and technology, providing me with a solid foundation in blending computational thinking with strategic decision-making.

To enhance my business intelligence and managerial skills, I completed a Master of Business Administration - MBA (2010) program at Ladoke Akintola University of Technology. This program equipped me with the necessary tools to develop and manage complex financial applications, bridging the gap between technology and business.

Prior to my Master degrees, I furthered my knowledge in Computer Science with a Post Graduate Diploma from Lagos State University. This program honed my technical expertise and solidified my understanding of core computing concepts.

My commitment to professional growth is highlighted by my membership in prestigious organizations:

ؠ I am a Fellow of Nigeria Computer Society (NCS). As a Fellow of NCS, I have been recognized for my significant contributions to the advancement of computing knowledge and practice.

ؠ I am chartered IT Professional and Member of Computer Professionals (Registration Council of Nigeria) demonstrating a commitment to ethical and professional standards in the IT industry.

ؠ I am a Member of the Association for Computing Machinery (ACM), showcases my engagement with a global community of computing professionals, fostering learning and collaboration, reflecting my dedication to upholding professional standards and contributing to the growth of the computing field.

These affiliations reflect my dedication to ethical and responsible practice, as well as my contribution to the advancement of the field.

To learn more about me, please visit:

<https://www.linkedin.com/in/dele-adelusi/>
