---
title: "Personal Statement" 
editor: visual 
---

My sincerest desire to become a Professor of Computer Science growing up with deep and sound knowledge of Mathematics right from my elementary school to high school has really helped me to enjoy and be very delightful in solving complex problems. This has been my dream and driving force behind my chosen field of career which led to my keen interest in studying computer science, ways of logical processing and complex problem solving.

In pursuing computer science I have been fascinated by technologies in general and computers in particular from the beginning. In fact, I quickly picked up interest in programming/software development starting with DOS, QBasic, FORTRAN, COBOL, Pascal, C-language etc as soon as I got admission into high institution.

In furthering my keen desire for computer science, I am having a **Master in Social Data Analytics and Research** from University of Texas at Dallas in view. I had **Master in Business Computing** (2018) from University of Ibadan -- Nigeria.  To complement my business knowledge and exposure, and develop and manage a robust financial application, I had **Master of Business Administration** -- (2008) from Ladoke Akintola University of Technology -- Nigeria. Prior to Master degrees, I graduated with Post Graduate Diploma in Computer Science (2008) from Lagos State University, Nigeria. I graduated from Computer science (2001) major with degree from Yaba College of Technology, Nigeria where I began my Computer Science journey. I am ***Chartered IT Professional*** and a Member of Computer Professionals (Registration Council of Nigeria) and a Fellow of Nigeria Computer Society (NCS). I am also a Member of Association for Computing Machinery.

My working career gave me opportunity to develop strategies, oversee the design, development and implementation of major systems initiatives, manage and oversee multiple, concurrent and often disparate tasks for projects involving innovative software applications and highly complex system integration.

I am a dynamic and seasoned IT professional with cognate work experience gained through several developed & managed IT projects. I have my core competence in Software Development, Database Management and Data Science. Over the years working as an IT Professional, IT Manager and IT Consultant, I have exposure and ground knowledge in Database Management, Software development/Programming, System Analysis & Design, System Auditing, Networking, Web Designing/development, Information/Computer Security, and Business Continuity & Disaster Recovery Management. Some of the Software I built and in use are Accounting Management System, Hospital Operation Management System, Sales/Procurement Management System, Facility Booking System, Financial Remittance/Reporting System, School Management System, Homecell Reports Management System, E-Billing/Revenue Management System, Membership Management Portal, Personnel & Payroll Management System.

I gladly excelled and acquired deep knowledge in this my choosing course of studies which I have partly educated my classmates, colleagues in form of tutorials, practicals, capacity building.

Upon achieving my objectives, I wish to further my dreams by continuing studies with ***Doctor of Philosophy - PhD (Computer Science)*** with focus on Data Science at University of Texas at Arlington.

Research has been an integral part of my professional development. I specialized in software development, database management and data analytics to mention a few. My history in teaching, research, and impacting IT knowledge blend well with my degrees and open doors to study further in Doctor of Philosophy (PhD) in Computer Science with focus on Data Science.

In the rapidly evolving landscape of technology, I have been captivated by the power of data to drive innovation and transform industries. With a fervent desire to explore the frontiers of knowledge, I have applied for the Computer Science PhD program with a dedicated focus on Data Science. My academic journey and professional experiences have prepared me to embark on this rigorous path of research and discovery.

Whatever mind can conceive, it can achieve with strong determination and focus. Throughout my career, I have consistently delivered values and driven business objectives through the strategic applications of Information Technology. As a Software/Web Developer and Data Scientist, I have specialized in and gained significant experience in all stages of the development cycle for dynamic Software projects. My expertise extends to ASP.NET, Python, SQL Server, HTML, JavaScript, R, RStudio, Tableau, .NET Core, Crystal Report, SSRS, and various other technologies and frameworks. By leveraging these skills, I have successfully implemented innovative solutions and contributed to the growth and success of organizations.

Big Data and Cloud computing has received a considerable development as a promising approach for delivering Information and Communication Technologies services. The profound impacts that data-driven insights can have on decision-making, efficiency, and predictive accuracy ignited a passion within me to delve deeper into this field. Intelligent big data analytic in cloud computing environment that require improvement are my areas of interest to carry out my researches and contribute to knowledge domain in helping health care Industry in early detection of chronic diseases. Advanced data analysis techniques allow for more accurate and efficient diagnoses. Machine learning algorithms assist in interpreting medical images (such as X-rays, MRIs, and CT scans), improving accuracy and reducing human error.

To prepare for the challenges of doctoral research, I have consistently sought to broaden my skills. I have engaged in advanced coursework in machine learning, statistics, and algorithm design, refining my analytical and computational abilities. Big Data is a huge volume of unstructured, semi structured and structured data which possible to analyze and mine information from large datasets.

Cloud computing is the on-demand delivery of compute power, database storage, applications, and other IT resources through a cloud services platform via the internet. With the fast development of processing, storage technologies, the sensation of the Internet, and computing resources have become cheaper, more powerful and more universally available than ever before.

Recently, I completed DevOps course with knowledge advantage in AzureDevOps and Cloud computing. Interestingly, I have four (4) different Amazon Web Services (AWS) Certifications and Azure which are good strong and secure cloud services platform, offering compute power, database storage, content delivery and other functionality to help business scale and grow in term of cloud computing.

The bottom line is that I want to be a part of this exciting field. The University of Texas at Arlington has a good reputation and has produced significant contributors to the field. A Doctor of Philosophy (Computer Science) degree from the University will avail opportunities for me and let me contribute more effectively than I have in the past.

In conclusion, I am driven by an unwavering passion for data science and its potential to reshape industries, drive innovation, and enrich our understanding of the world. A PhD in Computer Science with a focus on Data Science from University of Texas at Arlington would provide me with the ideal platform to realize these ambitions. I am excited to contribute to the ongoing research efforts at the intersection of data science and machine learning, while also nurturing a lifelong commitment to learning, collaboration, and innovation.

Thank you.

To learn more about me, please visit:

<https://www.linkedin.com/in/dele-adelusi/>
