---
title: "Research"
editor: visual
---

I am a Master student studying Social Data Analytics. My research topic is on Machine Learning for Public Healthcare.

Interests: Data Science - Machine Learning - Deep Learning, Data Analytics

Data Science and Software Development indeed play crucial roles in advancing healthcare, particularly in early disease detection and treatment. Data Analytics and Research play a significant role in the health industry by providing insights into various aspects of public health, patient behavior, healthcare utilization, and more. Incorporating data analytics and research into the health industry enables a more comprehensive understanding of the factors influencing health and healthcare delivery.

The health industry is undergoing a transformative shift, driven by the integration of software development, artificial intelligence, machine learning data analytics and research. These tools, once confined to traditional research settings, have now become essential components of healthcare delivery, policy-making, and disease prevention. Data analytics and research have ushered in a new era of evidence-based decision-making, personalized treatment approaches, and proactive health management.

Data Science can analyze large amounts of medical data, such as patient records, genetic information, and diagnostic images, to identify patterns and indicators that might predict the onset of diseases. Machine learning models can be trained to recognize early signs of diseases like cancer, diabetes, and heart conditions, enabling timely intervention and treatment.

As an experienced Software Developer and Data Scientist, Artificial Intelligence, Machine learning and Data Analytics are the main areas of my current data science research study which focuses on deep learning. Deep learning is a subfield of machine learning that focuses on artificial neural networks and algorithms inspired by the structure and function of the human brain. It involves training deep neural networks with multiple layers to learn and make predictions or decisions from large amounts of data.

Deep learning, a subset of machine learning, has significant research importance in the United States in its application to the health care sector.

Therefore, based on my wealth of experience and demonstrated skills in Software Development and Data Science, my proposed endeavor aims to benefit the United States health industry by utilizing data analytics, artificial intelligence (AI), and machine learning techniques using a variety of data sources, such as electronic health records (EHRs), wearable devices, genetic databases, environmental data, and patient-reported information, **to identify people at high risk of developing chronic diseases at an early stage**.

To learn more information about me, please visit:

https://www.linkedin.com/in/dele-adelusi
